// Code generated by MockGen. DO NOT EDIT.
// Source: idp.go
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=../../mocks/core/idp_mocks.go -source=idp.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/slashdevops/idp-scim-sync/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockIdentityProviderService is a mock of IdentityProviderService interface.
type MockIdentityProviderService struct {
	ctrl     *gomock.Controller
	recorder *MockIdentityProviderServiceMockRecorder
	isgomock struct{}
}

// MockIdentityProviderServiceMockRecorder is the mock recorder for MockIdentityProviderService.
type MockIdentityProviderServiceMockRecorder struct {
	mock *MockIdentityProviderService
}

// NewMockIdentityProviderService creates a new mock instance.
func NewMockIdentityProviderService(ctrl *gomock.Controller) *MockIdentityProviderService {
	mock := &MockIdentityProviderService{ctrl: ctrl}
	mock.recorder = &MockIdentityProviderServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdentityProviderService) EXPECT() *MockIdentityProviderServiceMockRecorder {
	return m.recorder
}

// GetGroupMembers mocks base method.
func (m *MockIdentityProviderService) GetGroupMembers(ctx context.Context, id string) (*model.MembersResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupMembers", ctx, id)
	ret0, _ := ret[0].(*model.MembersResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupMembers indicates an expected call of GetGroupMembers.
func (mr *MockIdentityProviderServiceMockRecorder) GetGroupMembers(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupMembers", reflect.TypeOf((*MockIdentityProviderService)(nil).GetGroupMembers), ctx, id)
}

// GetGroups mocks base method.
func (m *MockIdentityProviderService) GetGroups(ctx context.Context, filter []string) (*model.GroupsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroups", ctx, filter)
	ret0, _ := ret[0].(*model.GroupsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroups indicates an expected call of GetGroups.
func (mr *MockIdentityProviderServiceMockRecorder) GetGroups(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroups", reflect.TypeOf((*MockIdentityProviderService)(nil).GetGroups), ctx, filter)
}

// GetGroupsMembers mocks base method.
func (m *MockIdentityProviderService) GetGroupsMembers(ctx context.Context, gr *model.GroupsResult) (*model.GroupsMembersResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupsMembers", ctx, gr)
	ret0, _ := ret[0].(*model.GroupsMembersResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupsMembers indicates an expected call of GetGroupsMembers.
func (mr *MockIdentityProviderServiceMockRecorder) GetGroupsMembers(ctx, gr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupsMembers", reflect.TypeOf((*MockIdentityProviderService)(nil).GetGroupsMembers), ctx, gr)
}

// GetUsers mocks base method.
func (m *MockIdentityProviderService) GetUsers(ctx context.Context, filter []string) (*model.UsersResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsers", ctx, filter)
	ret0, _ := ret[0].(*model.UsersResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsers indicates an expected call of GetUsers.
func (mr *MockIdentityProviderServiceMockRecorder) GetUsers(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsers", reflect.TypeOf((*MockIdentityProviderService)(nil).GetUsers), ctx, filter)
}

// GetUsersByGroupsMembers mocks base method.
func (m *MockIdentityProviderService) GetUsersByGroupsMembers(ctx context.Context, gmr *model.GroupsMembersResult) (*model.UsersResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersByGroupsMembers", ctx, gmr)
	ret0, _ := ret[0].(*model.UsersResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersByGroupsMembers indicates an expected call of GetUsersByGroupsMembers.
func (mr *MockIdentityProviderServiceMockRecorder) GetUsersByGroupsMembers(ctx, gmr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersByGroupsMembers", reflect.TypeOf((*MockIdentityProviderService)(nil).GetUsersByGroupsMembers), ctx, gmr)
}
