// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/slashdevops/idp-scim-sync/internal/model"
)

// MockStateRepository is a mock of StateRepository interface.
type MockStateRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStateRepositoryMockRecorder
}

// MockStateRepositoryMockRecorder is the mock recorder for MockStateRepository.
type MockStateRepositoryMockRecorder struct {
	mock *MockStateRepository
}

// NewMockStateRepository creates a new mock instance.
func NewMockStateRepository(ctrl *gomock.Controller) *MockStateRepository {
	mock := &MockStateRepository{ctrl: ctrl}
	mock.recorder = &MockStateRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStateRepository) EXPECT() *MockStateRepositoryMockRecorder {
	return m.recorder
}

// GetGroups mocks base method.
func (m *MockStateRepository) GetGroups() (*model.GroupsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroups")
	ret0, _ := ret[0].(*model.GroupsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroups indicates an expected call of GetGroups.
func (mr *MockStateRepositoryMockRecorder) GetGroups() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroups", reflect.TypeOf((*MockStateRepository)(nil).GetGroups))
}

// GetGroupsUsers mocks base method.
func (m *MockStateRepository) GetGroupsUsers() (*model.GroupsUsersResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupsUsers")
	ret0, _ := ret[0].(*model.GroupsUsersResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupsUsers indicates an expected call of GetGroupsUsers.
func (mr *MockStateRepositoryMockRecorder) GetGroupsUsers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupsUsers", reflect.TypeOf((*MockStateRepository)(nil).GetGroupsUsers))
}

// GetState mocks base method.
func (m *MockStateRepository) GetState() (model.State, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetState")
	ret0, _ := ret[0].(model.State)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetState indicates an expected call of GetState.
func (mr *MockStateRepositoryMockRecorder) GetState() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetState", reflect.TypeOf((*MockStateRepository)(nil).GetState))
}

// GetUsers mocks base method.
func (m *MockStateRepository) GetUsers() (*model.UsersResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsers")
	ret0, _ := ret[0].(*model.UsersResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsers indicates an expected call of GetUsers.
func (mr *MockStateRepositoryMockRecorder) GetUsers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsers", reflect.TypeOf((*MockStateRepository)(nil).GetUsers))
}

// StoreGroups mocks base method.
func (m *MockStateRepository) StoreGroups(gr *model.GroupsResult) (model.StoreGroupsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreGroups", gr)
	ret0, _ := ret[0].(model.StoreGroupsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StoreGroups indicates an expected call of StoreGroups.
func (mr *MockStateRepositoryMockRecorder) StoreGroups(gr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreGroups", reflect.TypeOf((*MockStateRepository)(nil).StoreGroups), gr)
}

// StoreGroupsUsers mocks base method.
func (m *MockStateRepository) StoreGroupsUsers(gr *model.GroupsUsersResult) (model.StoreGroupsUsersResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreGroupsUsers", gr)
	ret0, _ := ret[0].(model.StoreGroupsUsersResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StoreGroupsUsers indicates an expected call of StoreGroupsUsers.
func (mr *MockStateRepositoryMockRecorder) StoreGroupsUsers(gr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreGroupsUsers", reflect.TypeOf((*MockStateRepository)(nil).StoreGroupsUsers), gr)
}

// StoreState mocks base method.
func (m *MockStateRepository) StoreState(sgr *model.StoreGroupsResult, sur *model.StoreUsersResult, sgur *model.StoreGroupsUsersResult) (model.StoreStateResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreState", sgr, sur, sgur)
	ret0, _ := ret[0].(model.StoreStateResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StoreState indicates an expected call of StoreState.
func (mr *MockStateRepositoryMockRecorder) StoreState(sgr, sur, sgur interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreState", reflect.TypeOf((*MockStateRepository)(nil).StoreState), sgr, sur, sgur)
}

// StoreUsers mocks base method.
func (m *MockStateRepository) StoreUsers(ur *model.UsersResult) (model.StoreUsersResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreUsers", ur)
	ret0, _ := ret[0].(model.StoreUsersResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StoreUsers indicates an expected call of StoreUsers.
func (mr *MockStateRepositoryMockRecorder) StoreUsers(ur interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreUsers", reflect.TypeOf((*MockStateRepository)(nil).StoreUsers), ur)
}
