// Code generated by MockGen. DO NOT EDIT.
// Source: identity_provider.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	admin "google.golang.org/api/admin/directory/v1"
)

// MockGoogleProviderService is a mock of GoogleProviderService interface.
type MockGoogleProviderService struct {
	ctrl     *gomock.Controller
	recorder *MockGoogleProviderServiceMockRecorder
}

// MockGoogleProviderServiceMockRecorder is the mock recorder for MockGoogleProviderService.
type MockGoogleProviderServiceMockRecorder struct {
	mock *MockGoogleProviderService
}

// NewMockGoogleProviderService creates a new mock instance.
func NewMockGoogleProviderService(ctrl *gomock.Controller) *MockGoogleProviderService {
	mock := &MockGoogleProviderService{ctrl: ctrl}
	mock.recorder = &MockGoogleProviderServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGoogleProviderService) EXPECT() *MockGoogleProviderServiceMockRecorder {
	return m.recorder
}

// GetUser mocks base method.
func (m *MockGoogleProviderService) GetUser(userID string) (*admin.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", userID)
	ret0, _ := ret[0].(*admin.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockGoogleProviderServiceMockRecorder) GetUser(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockGoogleProviderService)(nil).GetUser), userID)
}

// ListGroupMembers mocks base method.
func (m *MockGoogleProviderService) ListGroupMembers(groupID string) ([]*admin.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGroupMembers", groupID)
	ret0, _ := ret[0].([]*admin.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGroupMembers indicates an expected call of ListGroupMembers.
func (mr *MockGoogleProviderServiceMockRecorder) ListGroupMembers(groupID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGroupMembers", reflect.TypeOf((*MockGoogleProviderService)(nil).ListGroupMembers), groupID)
}

// ListGroups mocks base method.
func (m *MockGoogleProviderService) ListGroups(query []string) ([]*admin.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGroups", query)
	ret0, _ := ret[0].([]*admin.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGroups indicates an expected call of ListGroups.
func (mr *MockGoogleProviderServiceMockRecorder) ListGroups(query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGroups", reflect.TypeOf((*MockGoogleProviderService)(nil).ListGroups), query)
}

// ListUsers mocks base method.
func (m *MockGoogleProviderService) ListUsers(query []string) ([]*admin.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", query)
	ret0, _ := ret[0].([]*admin.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockGoogleProviderServiceMockRecorder) ListUsers(query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockGoogleProviderService)(nil).ListUsers), query)
}
