name: "Build"

on:
  # push:
  #   branches:
  #     - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: "Test and Build"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    env:
      MAKE_DEBUG: "true"
    steps:
      - name: Check out code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0

      - name: Set up Go 1.x
        id: go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e  # v7.0.0
        with:
          go-version-file: ./go.mod

      - name: Go version
        run: |
          go version

      - name: Test
        run: make test

      - name: codecov coverage report
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f  # v7.0.0
        with:
          files: ./coverage.out

      - name: govulncheck
        uses: golang/govulncheck-action@032d45514ae346b1db93c04b0c90b841c370344f  # v1.1.0
        with:
          go-version-file: ./go.mod
          repo-checkout: false

      - name: Build
        run: make build
