name: "Container Image"

on:
  workflow_call:
  workflow_dispatch:

env:
  MAKE_STOP_ON_ERRORS: true
  MAKE_DEBUG: true

permissions:
  id-token: write
  contents: write
  packages: write

jobs:
  build:
    name: Build and Publish Container Images
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      - name: Tools and versions
        run: |
          echo "# Container Image Summary" > $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## Tools and versions" >> $GITHUB_STEP_SUMMARY

          podman_version=$(podman --version | awk '{print $3}')
          echo "Podman version: $podman_version"
          echo "**Podman Version:** $podman_version" >> $GITHUB_STEP_SUMMARY

          make_version=$(make --version | head -n 1)
          echo "Make version: $make_version"
          echo "**Make Version:** $make_version" >> $GITHUB_STEP_SUMMARY

      - name: Download Distribution files
        uses: actions/download-artifact@v7
        with:
          name: dist
          path: ./dist/

      - name: Make container-build
        run: |
          echo "## Make container-build" >> $GITHUB_STEP_SUMMARY
          GIT_VERSION=${{ github.ref_name }} make container-build | tee -a $GITHUB_STEP_SUMMARY

      - name: Show container images
        run: |
          echo "## Show container images" >> $GITHUB_STEP_SUMMARY
          podman images | tee -a $GITHUB_STEP_SUMMARY

      - name: Make container-login
        run: |
          echo "## Make container-login" >> $GITHUB_STEP_SUMMARY
          GIT_VERSION=${{ github.ref_name }} REPOSITORY_REGISTRY_TOKEN=${{ secrets.GITHUB_TOKEN }} REPOSITORY_REGISTRY_USERNAME=${{ github.actor }} make container-login | tee -a $GITHUB_STEP_SUMMARY

      - name: Make container-publish
        run: |
          echo "## Make container-publish" >> $GITHUB_STEP_SUMMARY
          GIT_VERSION=${{ github.ref_name }} make container-publish | tee -a $GITHUB_STEP_SUMMARY
